name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-15

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28b
          add-to-path: true
      - name: Setup Go-1.22.x
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.22.x'
        
      - name: Build aar
        run: make

      - name: Tag release
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.version }}',
              sha: context.sha
            })

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: ./build/libxray-go-android.aar
